# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-06 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratingApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'In-active'), ('D', 'Deleted')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'In-active'), ('D', 'Deleted')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('http_method', models.CharField(max_length=100)),
                ('response_time', models.DecimalField(decimal_places=4, max_digits=10)),
                ('integrating_app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='intelliroute.IntegratingApp')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
