# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-06 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intelliroute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestaudit',
            name='http_method',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='requestaudit',
            name='integrating_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrating_app', to='intelliroute.IntegratingApp'),
        ),
    ]
