# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-06 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelliroute', '0002_auto_20190906_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integratingapp',
            name='alias',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
