# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-06 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelliroute", "0005_integratingapp_base_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestaudit",
            name="response_time",
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
