# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-07 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelliroute", "0007_auto_20190907_0721"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestaudit",
            name="http_method",
            field=models.CharField(
                choices=[
                    ("GET", "Get"),
                    ("POST", "Post"),
                    ("PUT", "Put"),
                    ("DELETE", "Delete"),
                    ("PATCH", "Patch"),
                ],
                max_length=6,
            ),
        ),
    ]
