# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-07 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("intelliroute", "0008_auto_20190907_0852"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalRequestAudit",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "Active"), ("I", "In-active"), ("D", "Deleted")],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "request_url",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "http_method",
                    models.CharField(
                        choices=[
                            ("GET", "Get"),
                            ("POST", "Post"),
                            ("PUT", "Put"),
                            ("DELETE", "Delete"),
                            ("PATCH", "Patch"),
                        ],
                        max_length=6,
                    ),
                ),
                ("response_time", models.DecimalField(decimal_places=8, max_digits=10)),
                (
                    "response_code",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "integrating_app",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="intelliroute.IntegratingApp",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical request audit",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
